#!/usr/bin/env bash
# Deploy the SuperTech corporate email footer assets to the Mailcow server.
#
# The postfix container bind-mounts data/conf/postfix -> /opt/postfix/conf, so
# copying into data/conf/postfix/disclaimer/ is immediately visible in the
# container. The content-filter script (footer-filter.py) is picked up on the
# next message with no reload; a reload is only needed after master.cf changes.
#
# Also installs footer-api.env (API key for mailbox owner lookup) from
# /root/mailcow-credentials.txt on the server — never committed to git.
#
# One-time master.cf wiring (footerfilter pipe + content_filter on submission
# services) is NOT done here — see docs/EMAIL_FOOTER.md.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVER="root@161.97.182.204"
MAILCOW="/opt/mailcow-dockerized"
EMAIL_DIR="$ROOT/branding/email"
REMOTE_DIR="${MAILCOW}/data/conf/postfix/disclaimer"

echo "==> Uploading email footer assets to ${REMOTE_DIR}"
ssh "${SERVER}" "mkdir -p ${REMOTE_DIR}"
scp "${EMAIL_DIR}/footer-filter.py"      "${SERVER}:${REMOTE_DIR}/footer-filter.py"
scp "${EMAIL_DIR}/corporate-footer.html" "${SERVER}:${REMOTE_DIR}/corporate-footer.html"
scp "${EMAIL_DIR}/corporate-footer.txt"  "${SERVER}:${REMOTE_DIR}/corporate-footer.txt"

# Publish the logo at the HTTPS URL used by email clients. The footer references
# this web copy so Gmail does not expose it as a MIME attachment.
if [[ -f "$ROOT/branding/mailcow-ui/supertech-logo.png" ]]; then
  ssh "${SERVER}" "mkdir -p ${MAILCOW}/data/web/img"
  scp "$ROOT/branding/mailcow-ui/supertech-logo.png" "${SERVER}:${MAILCOW}/data/web/img/supertech-logo.png"
  scp "$ROOT/branding/mailcow-ui/supertech-logo.png" "${SERVER}:${REMOTE_DIR}/supertech-logo.png"
fi

echo "==> Installing footer-api.env (API key for mailbox owner lookup)"
ssh "${SERVER}" bash -s << 'REMOTE'
set -euo pipefail
REMOTE_DIR="/opt/mailcow-dockerized/data/conf/postfix/disclaimer"
API_KEY=$(grep ^API_KEY= /root/mailcow-credentials.txt | cut -d= -f2-)
if [[ -z "${API_KEY}" ]]; then
  echo "ERROR: API_KEY not found in /root/mailcow-credentials.txt" >&2
  exit 1
fi
umask 077
cat > "${REMOTE_DIR}/footer-api.env" << EOF
# Generated by deploy-email-footer.sh — do not commit
API_KEY=${API_KEY}
API_BASE=https://nginx-mailcow
EOF
# The Postfix pipe service runs as nobody (uid/gid 65534), so grant that
# container group read access without making the API key world-readable.
chown 0:65534 "${REMOTE_DIR}/footer-api.env"
chmod 640 "${REMOTE_DIR}/footer-api.env"
REMOTE

echo "==> Setting permissions"
ssh "${SERVER}" "chmod 755 ${REMOTE_DIR}/footer-filter.py && chmod 644 ${REMOTE_DIR}/corporate-footer.* ${REMOTE_DIR}/supertech-logo.png 2>/dev/null || true && chown 0:65534 ${REMOTE_DIR}/footer-api.env && chmod 640 ${REMOTE_DIR}/footer-api.env"

echo "==> Done."
echo "    Filter changes are live immediately (pipe spawns a fresh process per message)."
echo "    If this is the first install, wire master.cf once — see docs/EMAIL_FOOTER.md."
echo "    Set mailbox owners with: ./scripts/set-mailbox-owner.sh EMAIL \"Name\" \"Title\" \"Phone\""
